name: Android Debug APK

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Download Android SDK
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 34
          target: google_apis_playstore
      - name: Build Debug APK
        run: ./gradlew assembleDebug --no-daemon
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: salmani-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
